apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: react-app
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
    - name: react-app-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  externalIPs:
    - 192.168.4.101
  loadBalancerIP: 192.168.0.209
