apiVersion: v1
kind: Service
metadata:
  name: testmecsharp
  namespace: testmecsharp
spec:
  selector:
    app: testmecsharp
  type: LoadBalancer
  ports:
    - name: testmecsharp-port
      protocol: TCP
      port: 4200
      targetPort: 4200
